# Model Comparison

This notebook compares Linear Regression, Ridge Regression, and Lasso Regression based on their predictive performance and coefficient behavior.

The models will be compared using MAE, MSE, RMSE, Training R², Testing R², and coefficient analysis.


In [7]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [4]:
df=pd.read_csv("../data/insurance.csv")
df.head()

,age,sex,bmi,children,smoker,region,charges
0,19,female,27.900,0,yes,southwest,16884.92400
1,18,male,33.770,1,no,southeast,1725.55230
2,28,male,33.000,3,no,southeast,4449.46200
3,33,male,22.705,0,no,northwest,21984.47061
4,32,male,28.880,0,no,northwest,3866.85520


In [6]:
X=df.drop("charges",axis=1)
y=df["charges"]

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...     
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [8]:
X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42)

,age,sex,bmi,children,smoker,region
560,46,female,19.950,2,no,northwest
1285,47,female,24.320,0,no,northeast
1142,52,female,24.860,0,no,southeast
969,39,female,34.320,5,no,southeast
486,54,female,21.470,3,no,northwest
...,...,...,...,...,...,...
1095,18,female,31.350,4,no,northeast
1130,39,female,23.870,5,no,southeast
1294,58,male,25.175,0,no,northeast
860,37,female,47.600,2,yes,southwest


In [9]:
X_train["sex"]=X_train["sex"].map({"female":0,"male":1})
X_test["sex"]=X_test["sex"].map({"female":0,"male":1})
X_train["smoker"]=X_train["smoker"].map({"yes":1,"no":0})
X_test["smoker"]=X_test["smoker"].map({"yes":1,"no":0})

In [10]:
X_train=pd.get_dummies(X_train,columns=["region"],drop_first=True,dtype=int)
X_test=pd.get_dummies(X_test,columns=["region"],drop_first=True,dtype=int)


In [11]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train[["age","bmi","children"]]=scaler.fit_transform(
    X_train[["age","bmi","children"]])
X_test[["age","bmi","children"]]=scaler.transform(
    X_test[["age","bmi","children"]])

In [12]:
linear_regression_model=LinearRegression()
linear_regression_model.fit(X_train,y_train)


,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [13]:
linear_regression_y_pred=linear_regression_model.predict(X_test)
linear_regression_y_pred

array([ 8969.55027444,  7068.74744287, 36858.41091155,  9454.67850053,
       26973.17345656, 10864.11316424,   170.28084136, 16903.45028662,
        1092.43093614, 11218.34318352, 28101.68455267,  9377.73460205,
        5263.0595179 , 38416.04221107, 40255.82339284, 37098.25353123,
       15240.39392306, 35912.88264434,  9112.52398703, 31461.92108909,
        3847.68845883, 10130.12001517,  2370.54189389,  7140.21550828,
       11301.76782638, 12961.65366224, 14509.47251876,  6159.8976107 ,
        9963.85857263,  2177.85718217,  9115.93673493, 13073.68932159,
        4561.82376202,  3408.20756033,  4459.81359745, 13032.06505076,
        1979.99357292,  8813.28303302, 33271.29124448, 32585.51583927,
        3908.76090964,  4326.10774721, 14142.81326533, 11423.45494846,
        8774.13955311, 12097.28051001,  5281.57353499,  3150.5596042 ,
       35494.46461214,  9150.1124786 , 15836.84575621,  2343.57470069,
       12364.78414194,  1482.29488266, 13389.06105161, 12573.57395972,
      

In [53]:
lin_mae=mean_absolute_error(y_test,linear_regression_y_pred)
print("The mean abosulte error is:",lin_mae);
lin_mse=mean_squared_error(y_test,linear_regression_y_pred)
print("The mean squared error is:",lin_mse);
lin_rmse = np.sqrt(lin_mse)
print("Root Mean Squared Error:", lin_rmse)
lin_r2=r2_score(y_test,linear_regression_y_pred)
print("The r2 score is:",lin_r2*100,"%");
n=X_test.shape[0]
p=X_test.shape[1]
lin_adjusted_r2=1-((1-lin_r2)*(n-1))/(n-p-1)
print("the adjusted_r2 is:",lin_adjusted_r2)

The mean abosulte error is: 4181.194473753652
The mean squared error is: 33596915.851361476
Root Mean Squared Error: 5796.284659276274
The r2 score is: 78.35929767120722 %
the adjusted_r2 is: 0.7769085898923679


In [20]:
linear_regression_y_pred_train=linear_regression_model.predict(X_train)
linear_regression_y_pred_train

array([ 7094.54007011,  8344.72998713,  9153.77419778, ...,
       11441.08519155, 37314.37460682, 11453.12102783], shape=(1070,))

In [47]:
lin_r2_train = r2_score(y_train, linear_regression_y_pred_train)
print("Training R² Score:", lin_r2_train)
lin_r2_test = r2_score(y_test, linear_regression_y_pred)
print("Testing R² Score:", lin_r2_test)

Training R² Score: 0.7417255854683333
Testing R² Score: 0.7835929767120722


In [25]:
from sklearn.linear_model import Ridge
model_ridge=Ridge(alpha=0.1)
model_ridge.fit(X_train,y_train)

,alpha,0.1
,fit_intercept,True
,copy_X,True
,max_iter,None
,tol,0.0001
,solver,'auto'
,positive,False
,random_state,None


In [27]:
y_pred_ridge=model_ridge.predict(X_test)
y_pred_ridge

array([ 8971.35219312,  7071.0448728 , 36845.95923146,  9457.72996213,
       26963.17682952, 10866.97183257,   173.65372961, 16904.99336665,
        1095.21479655, 11221.12714577, 28091.98960536,  9380.70832175,
        5266.76682105, 38405.61528575, 40244.70814066, 37087.89216503,
       15242.68754121, 35901.7738352 ,  9115.58956964, 31450.35334676,
        3852.0605484 , 10133.14964166,  2374.57549339,  7142.17225334,
       11303.73468406, 12962.60512195, 14510.75260876,  6162.72325711,
        9965.50797328,  2182.74760227,  9118.56027736, 13075.01625803,
        4565.55874041,  3411.40804211,  4463.62760179, 13033.85601922,
        1983.38832489,  8815.58391836, 33259.5326525 , 32575.74096407,
        3912.35782656,  4329.78890617, 14144.28402652, 11425.80526892,
        8778.24130984, 12099.82535262,  5284.44097639,  3153.9984279 ,
       35484.46990582,  9154.17182311, 15838.74428586,  2348.55791427,
       12366.42240435,  1485.87834392, 13392.14624557, 12575.63520645,
      

In [54]:
rid_mae=mean_absolute_error(y_test,y_pred_ridge)
print("The mean abosulte error is:",rid_mae);
rid_mse=mean_squared_error(y_test,y_pred_ridge)
print("The mean squared error is:",rid_mse);
rid_rmse = np.sqrt(rid_mse)
print("Root Mean Squared Error:", rid_rmse)
rid_r2=r2_score(y_test,y_pred_ridge)
print("The r2 score is:",rid_r2*100,"%");
n=X_test.shape[0]
p=X_test.shape[1]
rid_adjusted_r2=1-((1-rid_r2)*(n-1))/(n-p-1)
print("the adjusted_r2 is:",rid_adjusted_r2)


The mean abosulte error is: 4182.3861667098845
The mean squared error is: 33601518.31850328
Root Mean Squared Error: 5796.681664409672
The r2 score is: 78.3563330948802 %
the adjusted_r2 is: 0.7768780284298461


In [55]:
y_train_pred=model_ridge.predict(X_train)
rid_r2_train = r2_score(y_train, y_train_pred)
print("Training R² Score:", rid_r2_train)
rid_r2_test = r2_score(y_test, y_pred_ridge)
print("Testing R² Score:", rid_r2_test)

Training R² Score: 0.7417253725960109
Testing R² Score: 0.783563330948802


In [33]:
lasso_model=Lasso(alpha=100)
lasso_model.fit(X_train,y_train)


,alpha,100
,fit_intercept,True
,precompute,False
,copy_X,True
,max_iter,1000
,tol,0.0001
,warm_start,False
,positive,False
,random_state,None
,selection,'cyclic'


In [35]:
y_pred_lasso=lasso_model.predict(X_test)
y_pred_lasso

array([ 8.65326886e+03,  7.21177791e+03,  3.62676034e+04,  9.43396969e+03,
        2.65835825e+04,  1.10906023e+04,  6.12276276e+02,  1.66820876e+04,
        1.23034048e+03,  1.11052577e+04,  2.80414207e+04,  9.34551763e+03,
        5.67837651e+03,  3.76563256e+04,  3.96548589e+04,  3.64880749e+04,
        1.51268618e+04,  3.54135524e+04,  9.44999691e+03,  3.10137802e+04,
        4.30793639e+03,  1.04742998e+04,  3.07748839e+03,  6.76846827e+03,
        1.11772317e+04,  1.25466927e+04,  1.48043879e+04,  6.13587684e+03,
        9.59915323e+03,  2.74601842e+03,  9.39664384e+03,  1.30299267e+04,
        4.97537921e+03,  3.61927442e+03,  5.05601512e+03,  1.25226555e+04,
        2.67957998e+03,  9.27784547e+03,  3.27563902e+04,  3.22144663e+04,
        4.27627931e+03,  4.47735873e+03,  1.43748224e+04,  1.15403003e+04,
        8.95731351e+03,  1.25304084e+04,  5.29231976e+03,  3.72837337e+03,
        3.49110993e+04,  9.28233430e+03,  1.59301090e+04,  2.85759183e+03,
        1.21289789e+04,  

In [56]:
lasso_mae=mean_absolute_error(y_test,y_pred_lasso)
print("The mean abosulte error is:",lasso_mae);
lasso_mse=mean_squared_error(y_test,y_pred_lasso)
print("The mean squared error is:",lasso_mse);
lasso_rmse = np.sqrt(lasso_mse)
print("Root Mean Squared Error:", lasso_rmse)
lasso_r2=r2_score(y_test,y_pred_lasso)
print("The r2 score is:",lasso_r2*100,"%");
n=X_test.shape[0]
p=X_test.shape[1]
lasso_adjusted_r2=1-((1-lasso_r2)*(n-1))/(n-p-1)
print("the adjusted_r2 is:",lasso_adjusted_r2)

The mean abosulte error is: 4248.494464943583
The mean squared error is: 34266072.94587828
Root Mean Squared Error: 5853.722998731515
The r2 score is: 77.92827508694072 %
the adjusted_r2 is: 0.7724652296607402


In [57]:
y_train_pred=lasso_model.predict(X_train)
lasso_r2_train = r2_score(y_train, y_train_pred)
print("Training R² Score:", lasso_r2_train)
lasso_r2_test = r2_score(y_test, y_pred_lasso)
print("Testing R² Score:", lasso_r2_test)

Training R² Score: 0.7404650969661244
Testing R² Score: 0.7792827508694071


In [58]:
comparision=pd.DataFrame({
    "Models":["LinearRegression","RidgeRegression","LassoRegression"],
    "MAE":[lin_mae,rid_mae,lasso_mae],
    "MSE":[lin_mse,rid_mse,lasso_mse],
    "RMSE":[lin_rmse,rid_rmse,lasso_rmse],
    "Train R²": [lin_r2_train, rid_r2_train, lasso_r2_train],
    "Test R²": [lin_r2_test, rid_r2_test, lasso_r2_test]
})
comparision

,Models,MAE,MSE,RMSE,Train R²,Test R²
0,LinearRegression,4181.194474,3.359692e+07,5796.284659,0.741726,0.783593
1,RidgeRegression,4182.386167,3.360152e+07,5796.681664,0.741725,0.783563
2,LassoRegression,4248.494465,3.426607e+07,5853.722999,0.740465,0.779283


## Model Comparison Conclusion

Based on the evaluation metrics, Linear Regression performs slightly better than Ridge and Lasso Regression on this dataset.

Linear Regression achieved the lowest MAE, MSE, and RMSE and the highest Test R² among the three models.

Ridge Regression produced almost identical results to Linear Regression, indicating that the selected regularization strength had very little effect on model performance.

Lasso Regression performed slightly worse in terms of prediction error and Test R². However, Lasso provided feature selection by reducing some coefficients exactly to zero, resulting in a simpler model.

Therefore, for this dataset, Linear Regression provides the best predictive performance, while Lasso provides the advantage of automatic feature selection.